blank_issues_enabled: true
contact_links:
  - name: Discord dei TWR
    url: https://discord.gg/85ayAcHRfH
    about: Il gruppo che ha tradotto il gioco. Per parlare della traduzione, dei testi, o solo per fare due chiacchiere.
